services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    image: pdf-qa-chatbot-backend:26.1

    container_name: pdf-qa-chatbot-backend

    env_file:
      - .env

    environment:
      OLLAMA_BASE_URL: ${OLLAMA_DOCKER_BASE_URL}
    ports:
      - "8000:8000"

    restart: unless-stopped
    